if answer has same rating in two or three answer it wont guess you wi…
SubhamTyagi/loco-answers pull request #460
Opened 2020-06-15 01:47 UTC by rollychop

…ll guess the answer

removed "." from option for better matching (it might mis behave )

2020-06-25 08:45 UTC, SubhamTyagi commented on app/src/main/java/ai/loko/hk/ui/MainActivity.java
> +                        "/loco-answers/master/update-changelog.json")
Why??

2020-06-25 08:46 UTC, SubhamTyagi commented on app/src/main/java/ai/loko/hk/ui/MainActivity.java
> +                                Uri.parse("https://github.com/rollychop/loco-answers/releases/")));
??

2020-06-25 08:54 UTC, SubhamTyagi requested changes

2020-06-25 08:54 UTC, SubhamTyagi commented on README.md
> +[![licence](https://img.shields.io/badge/Licence-GPLv3-red.svg)](https://github.com/rollychop/loco-answers/blob/master/LICENSE) ![version](https://img.shields.io/badge/Version-2.6.1-green.svg)[ ![Hit
Why this ??

2020-06-25 08:54 UTC, SubhamTyagi commented on README.md
> +* [Download latest Apk File](https://github.com/rollychop/loco-answers/releases)  ![GitHub All Releases](https://img.shields.io/github/downloads/SubhamTyagi/loco-answers/total.svg?style=social)
Same here!

2020-06-25 08:54 UTC, SubhamTyagi commented on app/build.gradle
> +        versionNameSuffix '-AginstChina'
Sentiments 😃

2020-06-25 08:54 UTC, SubhamTyagi commented on update-changelog.json
> +  "url": "https://github.com/rollychop/loco-answers/releases",
Why?? May be your repo stuf

2020-06-25 08:55 UTC, SubhamTyagi commented
Could you provide the apk file for this MR

2020-06-25 08:56 UTC, SubhamTyagi commented
> 
> 
> Negetive Question Notifier added

What is this? Could you explain this more

2020-06-26 09:02 UTC, rollychop commented
> > Negetive Question Notifier added
> 
> What is this? Could you explain this more

This will nothing just notify if question is negative or if default search engine fails it will notify
if src/main/res/layout/floating.xml changes then user will get more from above 
this will enable highlighting of negative questions and many more

2020-06-26 10:04 UTC, closed without merging